# Generated by Django 4.2.7 on 2023-12-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='role_id',
            new_name='role',
        ),
    ]
