# Generated by Django 4.2.7 on 2023-12-05 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_users_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_requested', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_access_requests', to='app.users')),
                ('super_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_admin_access_requests', to='app.users')),
            ],
        ),
    ]
